yellow_locations_routes = {
    ("A", "L", 1): "lfffrffffffrf",        #from T junction to end of dropping line
    ("A", "L", 2): "lfffrfffffrf",
    ("A", "L", 3): "lfffrffffrf",
    ("A", "L", 4): "lfffrfffrf",
    ("A", "L", 5): "lfffrffrf",
    ("A", "L", 6): "lfffrfrf",
    ("A", "U", 1): "rflfffffffflflfrfrflf",
    ("A", "U", 2): "rflfffffffflflfrfrfflf",
    ("A", "U", 3): "rflfffffffflflfrfrffflf",
    ("A", "U", 4): "rflfffffffflflfrfrfffflf",
    ("A", "U", 5): "rflfffffffflflfrfrffffflf",
    ("A", "U", 6): "rflfffffffflflfrfrfffffflf",
    ("B", "L", 1): "rflflf",
    ("B", "L", 2): "rflfflf",
    ("B", "L", 3): "rflffflf",
    ("B", "L", 4): "rflfffflf",
    ("B", "L", 5): "rflffffflf",
    ("B", "L", 6): "rflfffffflf",
    ("B", "U", 1): "rflfffffffflflflflffffffrf",
    ("B", "U", 2): "rflfffffffflflflflfffffrf",
    ("B", "U", 3): "rflfffffffflflflflffffrf",
    ("B", "U", 4): "rflfffffffflflflflfffrf",
    ("B", "U", 5): "rflfffffffflflflflffrf",
    ("B", "U", 6): "rflfffffffflflflflfrf"}